dt: 0.08 # sampling time

# car parameters mass, distance of CG from front (a) and rear (b) axis, height of CG, yaw moment of inertia
car:
  l: 3 # total length [m]
  m: 1700 #mass [kg]
  Izz: 3000 #inertia
  a: 1.1 # distance from front to CG [m]
  b: 1.4 # distance from rear to CG [m]
  h: 0.55 # CG height [m]
  eps: 0.85 # tire model modification
  Peng: 170000 #maximum engine power
  Xd: # drive force distribution
    f: 1
    r: 0
  Xb: # brake force distribution
    f: 0.78
    r: 0.22
  C_alpha: # cornering stiffness
    f: 180000
    r: 300000

# coefficients related to environment
env:
  Crr: 0.01 # rolling resistance coefficient https://en.wikipedia.org/wiki/Rolling_resistance
  Cd: 0.4243 # aerodynamic drag coefficient
  mu: # friction coefficient
    f: 0.9
    r: 0.95
  theta: 0 #TODO theta and phi are road grade and bank angle, but for now we assume flat track
  phi: 0
  Av2: 0 #because theta, phi are 0
  Frr: 220 #rolling resistance force