# prediction and control horizon
horizon: 50
mpc_dt: 0.03
horizon_pm: 0
mpc_dt_pm: 0.15
obstacles: False

# weights for the cost function
cost_weights:
  time: 1
  speed: 0.1
  ey: 0.5
  epsi: 1
  w:  0.2
  Fx: 0.00001
  Fy: 0.00001
  deviation_st: 0.0001
  boundary: 1
  slip : 1500
  obstacles: 1.6

# input constraints
input_constraints:
  w_min: -0.4
  w_max: 0.4
  mu_lim: 0.95

# state constraints
state_constraints:
  Ux_min: 3
  max_speed: 15
  delta_min: -0.45
  delta_max: 0.45
  ey_min: -3
  ey_max: 3