# track data
name: 'bean'

corners: # [x, y]
  - [0, 0]
  - [60, 0]
  - [60, 60]
  - [0, 40]
  - [-60, 60]
  - [-60, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [60, 2, 3]
  - [90,  3, 2]
  - [90, -3, 2]
  - [190, 0, 2]

resolution: 0.1
smoothing: 300
width: 9