# track data
wp_x:
  #start
  - 0

  # bottom segment
  - 50

  # right segment
  - 50

  # top segment
  - -50

  # left segment
  - -50

  # end
  - 0

wp_y:
  #start
  - 0

  # bottom segment
  - 0

  # right segment
  - 60

  # top segment
  - 60

  # left segment
  - 0

  # end
  - 0

resolution: 0.1
smoothing: 170
width: 8