# track data
wp_x:
  - -1
  - 0
  - 0
  - 1
  - 1
  - 2
  - 2
  - 3
  - 3
  - 1.5
  - 1.0
  - 0
  - -1
  - -2.5
  - -2.5
  - 0.16

wp_y:
  - -1.5 
  - -1.5
  - -0.5
  - -0.5
  - -1.5
  - -1.5
  - -0.5
  - -0.3
  - 0.7
  - 1.5
  - 1.5
  - 1.5
  - 0
  - -0.5
  - -1.5
  - -1.48

resolution: 0.02
smoothing: 30
width: 0.45