# track data
wp_x:
  - -50
  - 0
  - 0
  - 50
  - 50
  - 100
  - 100
  - 150
  - 150
  - 75
  - 0
  - -50
  - 0
  - 0
  - -50
  - -50
  - -10

wp_y:
  - -75
  - -75
  - -25
  - -25
  - -75
  - -75
  - -25
  - -15
  - 35
  - 50
  - 50
  - 0
  - 0
  - -30
  - -30
  - -75
  - -75

resolution: 0.1
smoothing: 200
width: 10