# track data
corners:
  - [0, 0]
  - [60, 0]
  - [60, 70]
  - [30, 70]
  - [-10, 48]
  - [-10, 60]
  - [-60, 48]
  - [-60, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [80, 3, 1.5]
  - [80, -3, 1.5]
  - [150, 0, 2]

resolution: 0.1
smoothing: 120
width: 9