# track data
corners:
  - [0, 0]

  # curve 1
  - [45, 0]
  - [60, 15]

  # curve 2
  - [60, 70]
  - [30, 70]

  # weird stuff
  - [-10, 52]
  - [-20, 60]
  - [-30, 70]
  - [-40, 60]
  - [-50, 50]

  # almost a curve
  - [-60, 35]
  - [-50, 30]
  
  # last curve
  - [-50, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [80, 3, 1.5]
  - [80, -3, 1.5]
  - [150, 0, 2]

resolution: 0.1
smoothing: 120
width: 9