# track data
name: 'ippodromo'

corners: # [x, y]
  - [0, 0]
  - [60, 0]
  - [60, 60]
  - [-60, 60]
  - [-60, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [30, 0, 5]
  # - [30, 0, 1]
  # - [60, 0, 2]
  # - [100,  3, 2]
  # - [100, -3, 2]
  # - [140, 0, 2]
  # - [170, -2.5, 2]
  # - [185, 2.5, 2]

resolution: 0.1
smoothing: 300
width: 9