# track data
wp_x:
  #start
  - 0

  # bottom segment
  - 60

  # right segment
  - 60

  # top segment
  - -60

  # left segment
  - -60

  # end
  - 35

wp_y:
  #start
  - 0

  # bottom segment
  - 0

  # right segment
  - 60

  # top segment
  - 60

  # left segment
  - 0

  # end
  - 0

resolution: 0.1
smoothing: 250
width: 9