# track data

corners: # [x, y]
  - [0, 0]
  - [45, 0]
  - [60, 15]
  - [60, 45]
  - [45, 60]
  - [-45, 60]
  - [-60, 45]
  - [-60, 15]
  - [-45, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [40, -3, 4]
  - [60, 3, 4]
  - [80, 3, 1.5]
  - [80, -3, 1.5]
  - [150, 0, 2]

resolution: 0.1
smoothing: 110
width: 9