# track data

corners:
  - [0, 0]
  - [45, 0]
  - [60, 15]
  - [60, 45]
  - [45, 60]
  - [-45, 60]
  - [-60, 45]
  - [-60, 15]
  - [-45, 0]
  - [0, 0]

curves: [False, True, False, True, False, True, False, True, False]

resolution: 0.1
smoothing: 110
width: 9