# track data

corners: # [x, y]
  - [0, 0]
  - [60, 0]
  - [80, 20]
  - [80, 60]
  - [60, 80]
  - [-60, 80]
  - [-80, 60]
  - [-80, 20]
  - [-60, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [60, 2, 3]
  - [90,  3, 2]
  - [90, -3, 2]
  - [190, 0, 2]

resolution: 0.1
smoothing: 130
width: 9