# track data
wp_x:
  # start
  - 0

  # bottom segment
  - 60

  # right segment
  - 60

  # top segment
  - 30
  - -10
  - -10
  - -60

  # left segment
  - -60

  # end
  - 0

wp_y:
  # start
  - 0

  # bottom segment
  - 0

  # right segment
  - 70

  # top segment
  - 70
  - 48
  - 60
  - 48

  # left segment
  - 0

  # end
  - 0

resolution: 0.1
smoothing: 170
width: 8