# track data

corners: # [x, y]
  - [0, 0]
  - [150, 0]

  - [150, 25]
  - [100, 50]
  - [75, 75]

  - [75, 100]
  - [100, 125]
  - [125, 150]

  - [150, 200]
  - [-100, 200]
  - [-100, 0]
  - [0, 0]

obstacle_data: # [s, ey, r]
  - [20, 0, 2]
  - [60, 0, 3]
  - [100,  3, 2]
  - [100, -3, 2]
  - [140, 0, 2]
  - [170, -2.5, 2]
  - [185, 2.5, 2]

resolution: 0.1
smoothing: 300
width: 9