# track data
wp_x:
  - -2
  - 2
  - 2
  - -2
  - -2
  - -0.5

wp_y:
  - 0
  - 0
  - 2
  - 2
  - 0
  - 0

resolution: 0.03
smoothing: 25
width: 0.4

# initial state
initial_state:
  x: -1.24812
  y: 0.0
  v: 1

# weights for the cost function
cost_weights:
  ey: 10
  epsi: 100
  deviation: 10
  boundary: 100

# input constraints
input_constraints:
  a_max: 3.0
  a_min: 0
  w_max: 4.0
  w_min: -4.0

# state constraints
state_constraints:
  v_max: 30
  v_min: 0
  delta_max: 3.0
  delta_min: 3.0

# prediction and control horizon
horizon: 10
mpc_dt: 0.03
model_dt: 0.05
