# track data
wp_x:
  - -2
  - 2
  - 2
  - -2
  - -2
  - -0.5

wp_y:
  - 0
  - 0
  - 2
  - 2
  - 0
  - 0

resolution: 0.03
smoothing: 25
width: 0.4

# initial state
initial_state:
  x: -1.24812
  y: 0.0
  v: 1

# weights for the cost function
cost_weights:
  time: 10
  ey: 10
  epsi: 100
  w: 0.1
  deviation: 10
  boundary: 200

# input constraints
input_constraints:
  a_max: 2
  a_min: -1 
  w_max: 2
  w_min: -2

# state constraints
state_constraints:
  v_max: 1
  v_min: 1
  delta_max: 3.0
  delta_min: -3.0
  ey_max: 0.2
  ey_min: -0.2

# prediction and control horizon
horizon: 30
mpc_dt: 0.006
model_dt: 0.05

# simulation
n_steps: 150
