# track data
wp_x:
  - -1
  - 0
  - 0
  - 0.75
  - 0.75
  - 1.5
  - 1.5
  - 3.0
  - 3.0
  - 1.5
  - 1.0
  - 0
  - -1
  - -2.5
  - -2.5
  - 0

wp_y:
  - -1.5 
  - -1.5
  - -0.5
  - -0.5
  - -1.5
  - -1.5
  - -0.5
  - -0.3
  - 0.7
  - 1.5
  - 1.5
  - 1.5
  - 0
  - -0.5
  - -1.5
  - -1.5

resolution: 0.03
smoothing: 15
width: 0.4

# initial state
initial_state:
  x: -0.5454
  y: -1.5
  v: 1

# weights for the cost function
cost_weights:
  time: 1
  ey: 10
  epsi: 100
  w: 0.1
  a: 0.01
  v: 50
  deviation: 20
  boundary: 200

# input constraints
input_constraints:
  a_max: 1
  a_min: -1
  w_max: 4
  w_min: -4

# state constraints
state_constraints:
  v_max: 3
  v_min: 1
  delta_max: 3.0
  delta_min: -3.0
  ey_max: 0.2
  ey_min: -0.2

# prediction and control horizon
horizon: 15
mpc_dt: 0.008
model_dt: 0.05

# simulation
n_steps: 40
