track_name: 'ippodromo'

controller_names:
  # - 'singletrack'
  - 'cascaded'

# It can be activated just if 
# there is one controller
slip_angle_plot: False

name: 'cascaded6'

save_gif: False
save_images: False
save_data: False
load: False
logging: False