track_name: 'ippodromo'

controller_names:
  - 'singletrack'
  # - 'cascaded'

obstacles: False

# It can be activated just if 
# there is one controller
slip_angle_plot: False

name: 'singletrack4'

save_gif: False
save_images: False
save_data: False
load: True
logging: False