track_name: 'ippodromo'

controller_names:
  - 'singletrack'
  # - 'cascaded'

obstacles: False

# It can be activated just if 
# there is one controller
slip_angle_plot: True

name: 'singletrack_slip_angle2'

save_gif: True
save_images: False
save_data: False
load: True
logging: False