# prediction and control horizon
horizon: 35
mpc_dt: 0.01  # TODO bigger than 0.01, everything breaks

# weights for the cost function
cost_weights:
  time: 1
  Ux: 0.1
  ey: 0.5
  epsi: 1
  w:  0.0001
  Fx: 0.002
  deviation: 0.001
  boundary: 1
  slip : 1000
  friction: 0.0000001

# input constraints
input_constraints:
  w_min: -0.4
  w_max: 0.4
  mu_lim: 0.9

# state constraints
state_constraints:
  Ux_min: 3
  Ux_max: 12
  delta_min: -0.5
  delta_max: 0.5
  ey_min: -4
  ey_max: 4