# prediction and control horizon
horizon: 25
mpc_dt: 0.01

# weights for the cost function
cost_weights:
  time: 0.1
  Ux: 0.1
  ey: 0.4
  epsi: 1
  w:  0.001
  Fx: 0.001
  deviation: 0.01
  boundary: 1
  slip : 1000
  friction: 0.0000001

# input constraints
input_constraints:
  w_min: -0.35
  w_max: 0.35
  mu_lim: 0.7

# state constraints
state_constraints:
  Ux_min: 3
  Ux_max: 20
  delta_min: -0.5
  delta_max: 0.5
  ey_min: -4
  ey_max: 4
