# prediction and control horizon
horizon: 15
mpc_dt: 0.008

# weights for the cost function
cost_weights:
  time: 0.1
  ey: 5
  epsi: 5
  w: 0.001
  Fx: 0.001
  Ux: 10
  deviation: 10
  boundary: 100
  slip : 10
  friction: 0.1

# input constraints
input_constraints:
  Fx_max: 2
  Fx_min: -8
  w_max: 4
  w_min: -4

# state constraints
state_constraints:
  Ux_max: 3
  Ux_min: 0.5
  delta_max: 2.0
  delta_min: -2.0
  ey_max: 0.3
  ey_min: -0.3
