# prediction horizon
horizon: 20
mpc_dt: 0.008

# weights for the cost function
cost_weights:
  time: 1
  ey: 0.5
  epsi: 1
  w: 0.0001
  a: 0.01
  v: 0.1
  deviation: 0.01
  boundary: 1

# input constraints
input_constraints:
  a_max: 10
  a_min: -10
  w_max: 2
  w_min: -2

# state constraints
state_constraints:
  v_max: 25
  v_min: 0.5
  delta_max: 1.5
  delta_min: -1.5
  ey_max: 3
  ey_min: -3