# prediction horizon
horizon: 25
mpc_dt: 0.01

# weights for the cost function
cost_weights:
  time: 1
  ey: 0.5
  epsi: 1
  w: 0.0001
  a: 0.01
  v: 0.1
  deviation: 0.01
  boundary: 1

# input constraints
input_constraints:
  a_min: -10
  a_max: 10
  w_min: -2
  w_max: 2

# state constraints
state_constraints:
  v_min: 0.5
  v_max: 25
  delta_min: -1
  delta_max: 1
  ey_min: -3
  ey_max: 3