# prediction and control horizon
horizon: 32
mpc_dt: 0.01 # TODO bigger than 0.01, everything breaks

# weights for the cost function
cost_weights:
  time: 1
  V: 0.1
  ey: 0.5
  epsi: 1
  Fx: 0.00001
  deviation: 0.01
  boundary: 1
  slip : 1000
  friction: 0.00001

# input constraints
input_constraints:
  mu_lim: 0.9

# state constraints
state_constraints:
  V_min: 3
  V_max: 12
  ey_min: -4
  ey_max: 4
