# prediction horizon
horizon: 40
mpc_dt: 0.03
obstacles: False

# weights for the cost function
cost_weights:
  time: 1
  ey: 0.1
  epsi: 0.1
  v: 0.1
  w: 0.000001 
  a: 0.001
  deviation: 0.001
  boundary: 5

# input constraints
input_constraints:
  a_min: -4
  a_max: 4
  w_min: -0.5
  w_max: 0.5

# state constraints
state_constraints:
  v_min: 0
  v_max: 20
  delta_min: -0.3
  delta_max: 0.3
  ey_min: -3
  ey_max: 3