# prediction and control horizon
horizon: 50
mpc_dt: 0.03
horizon_pm: 0
mpc_dt_pm: 0.08
obstacles: False

# weights for the cost function
cost_weights:
  time: 1
  speed: 0.2
  ey: 0.4
  epsi: 1
  w:  0.001
  Fx: 0.000001
  Fy: 0.000001
  deviation_st: 0.001
  deviation_pm: 0.001
  boundary: 1
  slip : 1
  friction: 0.0000001
  obstacles: 1.2
  obstacles_pm: 3

# input constraints
input_constraints:
  w_min: -0.4
  w_max: 0.4
  mu_lim: 0.95

# state constraints
state_constraints:
  Ux_min: 3
  max_speed: 20
  delta_min: -0.45
  delta_max: 0.45
  ey_min: -3
  ey_max: 3

state_pm_constraints:
  V_min: 3
  ey_min: -3
  ey_max: 3